### ISSUE TITLE
Para hacer

### ISSUE THREAD

**Issue by giuliano-marinelli** [lifex/GrageasMagicas#1]
- Verificar que se seleccionen grageas adyacentes.
- Hacer que los eliminadores eliminen toda la fila y columna cuando hay una gragea en medio de dos combinaciones.
- Poner variables para el puntaje.
- Crear supergrageas cuando estan en medio de dos combinaciones.
- Definir el comportamiento de las supergrageas.

**Comment by Martinnqn** [comment]
- Verificar que se seleccionen grageas adyacentes.

- [x] Poner variables para el puntaje.
- [x] Hacer que los eliminadores eliminen toda la fila y columna cuando hay una gragea en medio de dos combinaciones. (lo hice a partir de calcularCombos() en la clase Juego)
- [x] Crear supergrageas cuando estan en medio de dos combinaciones.
- [x] Definir el comportamiento de las supergrageas.
